In [4]:
import numpy as np
import pandas as pd

In [ ]:
# video link = https://learn.ineuron.ai/lesson/12th-March-Pandas-and-Numpy/622ced70528fc5011f55ff90/course/Full-Stack-Data-Science-Upcoming-batch/61b30b40b733d139bc0e7ffb/batch/61b30b40b733d139bc0e6ffe

# video name = 12th march pandas and numpy

In [2]:
pd.DataFrame({'col1' : [1,2,3,4,5],
            'col2' : [45,56,67,34,34],
            'col3' : "shudhanshu kumar krish ineuron one"
})

col1  col2                                col3
0     1    45  shudhanshu kumar krish ineuron one
1     2    56  shudhanshu kumar krish ineuron one
2     3    67  shudhanshu kumar krish ineuron one
3     4    34  shudhanshu kumar krish ineuron one
4     5    34  shudhanshu kumar krish ineuron one

In [3]:
# if i want splite the col3 so what i do.

df = pd.DataFrame({'col1' : [1,2,3,4,5],
            'col2' : [45,56,67,34,34],
            'col3' : "shudhanshu kumar krish ineuron one".split()
})


# like that 

In [4]:
df

col1  col2        col3
0     1    45  shudhanshu
1     2    56       kumar
2     3    67       krish
3     4    34     ineuron
4     5    34         one

In [5]:
# create a new column for store the square of the first column.


df['col4'] = df['col1']**2

In [6]:
df

col1  col2        col3  col4
0     1    45  shudhanshu     1
1     2    56       kumar     4
2     3    67       krish     9
3     4    34     ineuron    16
4     5    34         one    25

In [7]:
def test(a):
    return a**2

In [8]:
df['col4_4'] = df['col1'].apply(test)

In [9]:
df

col1  col2        col3  col4  col4_4
0     1    45  shudhanshu     1       1
1     2    56       kumar     4       4
2     3    67       krish     9       9
3     4    34     ineuron    16      16
4     5    34         one    25      25

In [12]:
def test1(a):
    if (a[0]== 's'):
         return 's'
    else:
        return 'z'


In [14]:
df['col6'] = df['col3'].apply(test1)

In [15]:
df

col1  col2        col3  col4  col4_4 col6
0     1    45  shudhanshu     1       1    s
1     2    56       kumar     4       4    z
2     3    67       krish     9       9    z
3     4    34     ineuron    16      16    z
4     5    34         one    25      25    z

In [16]:
import math

In [17]:
df['col8'] = df['col2'].apply(math.log)

In [18]:
df

col1  col2        col3  col4  col4_4 col6      col8
0     1    45  shudhanshu     1       1    s  3.806662
1     2    56       kumar     4       4    z  4.025352
2     3    67       krish     9       9    z  4.204693
3     4    34     ineuron    16      16    z  3.526361
4     5    34         one    25      25    z  3.526361

In [19]:
# i have a list 

l = ["shudh",1,2,3,4,5]



In [20]:
type(l)

list

In [24]:
# this list i will convert into array by use the array function of numpy.

np.array(l)


array(['shudh', '1', '2', '3', '4', '5'], dtype='<U11')

In [25]:
type(np.array(l))

numpy.ndarray

In [3]:
np.mat([1,2,3,4,5])

matrix([[1, 2, 3, 4, 5]])

In [4]:
a = [1,2,3,4,5]
np.asanyarray(a)

array([1, 2, 3, 4, 5])

In [7]:
np.mat(a)

matrix([[1, 2, 3, 4, 5]])

In [8]:
np.asanyarray(np.mat(a))

matrix([[1, 2, 3, 4, 5]])

In [ ]:
# numpy.fromfunction() function construct an array by executing a 
# function over each coordinate and the resulting array, therefore, 
# has a value fn(x, y, z) at coordinate (x, y, z).

In [12]:
np.fromfunction(lambda i,j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [14]:
np.fromfunction(lambda i, j: i*j, (4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [7]:
# when i use lambda function with three argument so is not work. 
# it will be genatere the arror.

np.mat(fromfunction(lambda i,j,z: i*j*z, (3,3,3)))


# it is not display three dimation matrix.


NameError: name 'fromfunction' is not defined

In [18]:
np.fromfunction(lambda i,j,z: i*j*z, (3,3,3))


array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 1., 2.],
        [0., 2., 4.]],

       [[0., 0., 0.],
        [0., 2., 4.],
        [0., 4., 8.]]])

In [10]:
np.fromfunction(lambda i,j,z,p: i*j*z*p, (4,3,2,2))


array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 1.]],

        [[0., 0.],
         [0., 2.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 2.]],

        [[0., 0.],
         [0., 4.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 3.]],

        [[0., 0.],
         [0., 6.]]]])

In [47]:
np.fromfunction(lambda i,j,z: i*j*z, (4,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 1.],
        [0., 2.]],

       [[0., 0.],
        [0., 2.],
        [0., 4.]],

       [[0., 0.],
        [0., 3.],
        [0., 6.]]])

In [22]:
a = np.fromfunction(lambda i,j,z: i*j*z, (4,3,2))


In [23]:
a

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 1.],
        [0., 2.]],

       [[0., 0.],
        [0., 2.],
        [0., 4.]],

       [[0., 0.],
        [0., 3.],
        [0., 6.]]])

In [24]:
# find out dimation of array 
a.ndim

3

In [25]:
# find the size of array 
# size is reprasent the number of elements of array

a.size

24

In [26]:
# find the shape of matrix or array.

a.shape

(4, 3, 2)

In [27]:
# If you want to know about the type of data, you have to write this command.

a.dtype

dtype('float64')

In [28]:
# can this data convert into dataframe 
a

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 1.],
        [0., 2.]],

       [[0., 0.],
        [0., 2.],
        [0., 4.]],

       [[0., 0.],
        [0., 3.],
        [0., 6.]]])

In [25]:
# try to convert this data into dataframe.

pd.DataFrame(a)

# this multidimation array is not suitable for create dataframe, so it will be genarete error.
# three dimensional array is not possible to convert into dataframe.


ValueError: Must pass 2-d input. shape=(4, 3, 2)

In [29]:
# but if i 2di ayyar convert into datafram so yes it will be work

a1 = np.fromfunction(lambda i,j: i*j, (4,3,))


In [30]:
pd.DataFrame(a1)

0    1    2
0  0.0  0.0  0.0
1  0.0  1.0  2.0
2  0.0  2.0  4.0
3  0.0  3.0  6.0

In [33]:
a1 = np.fromfunction(lambda i,j: i*j, (400,100),dtype = int)


In [34]:
a1

array([[    0,     0,     0, ...,     0,     0,     0],
       [    0,     1,     2, ...,    97,    98,    99],
       [    0,     2,     4, ...,   194,   196,   198],
       ...,
       [    0,   397,   794, ..., 38509, 38906, 39303],
       [    0,   398,   796, ..., 38606, 39004, 39402],
       [    0,   399,   798, ..., 38703, 39102, 39501]])

In [35]:
pd.DataFrame(a1)

0    1    2     3     4     5     6     7     8     9   ...     90  \
0     0    0    0     0     0     0     0     0     0     0  ...      0   
1     0    1    2     3     4     5     6     7     8     9  ...     90   
2     0    2    4     6     8    10    12    14    16    18  ...    180   
3     0    3    6     9    12    15    18    21    24    27  ...    270   
4     0    4    8    12    16    20    24    28    32    36  ...    360   
..   ..  ...  ...   ...   ...   ...   ...   ...   ...   ...  ...    ...   
395   0  395  790  1185  1580  1975  2370  2765  3160  3555  ...  35550   
396   0  396  792  1188  1584  1980  2376  2772  3168  3564  ...  35640   
397   0  397  794  1191  1588  1985  2382  2779  3176  3573  ...  35730   
398   0  398  796  1194  1592  1990  2388  2786  3184  3582  ...  35820   
399   0  399  798  1197  1596  1995  2394  2793  3192  3591  ...  35910   

        91     92     93     94     95     96     97     98     99  
0        0      0      0      0      0      0      0      0      0  
1       91     92     93     94     95     96     97     98     99  
2      182    184    186    188    190    192    194    196    198  
3      273    276    279    282    285    288    291    294    297  
4      364    368    372    376    380    384    388    392    396  
..     ...    ...    ...    ...    ...    ...    ...    ...    ...  
395  35945  36340  36735  37130  37525  37920  38315  38710  39105  
396  36036  36432  36828  37224  37620  38016  38412  38808  39204  
397  36127  36524  36921  37318  37715  38112  38509  38906  39303  
398  36218  36616  37014  37412  37810  38208  38606  39004  39402  
399  36309  36708  37107  37506  37905  38304  38703  39102  39501  

[400 rows x 100 columns]

In [43]:
np.random.rand(100,4)

array([[0.30026053, 0.21162332, 0.41399334, 0.08747674],
       [0.60147722, 0.47426806, 0.14101683, 0.33860912],
       [0.92162068, 0.43288896, 0.96673741, 0.34809306],
       [0.84647477, 0.4905169 , 0.55070019, 0.25202785],
       [0.15708336, 0.15359912, 0.33347144, 0.14962782],
       [0.72914777, 0.0918399 , 0.50959841, 0.50007029],
       [0.87772616, 0.07498261, 0.97455361, 0.20177504],
       [0.4864223 , 0.70971233, 0.91766204, 0.70029083],
       [0.12666236, 0.13335585, 0.44051695, 0.57488765],
       [0.72033357, 0.8343103 , 0.23652739, 0.59072291],
       [0.8955321 , 0.33401057, 0.51576135, 0.97411421],
       [0.45441802, 0.96932954, 0.64501422, 0.7824409 ],
       [0.32645685, 0.31805256, 0.34571328, 0.45088318],
       [0.65659983, 0.97231189, 0.5329273 , 0.66487264],
       [0.77018994, 0.31796487, 0.66276575, 0.55220352],
       [0.92214454, 0.8778056 , 0.05902643, 0.10034402],
       [0.45378226, 0.64689242, 0.02773579, 0.86524159],
       [0.34685235, 0.99233252,

In [41]:
np.random.randint(4,50)

41

In [44]:
np.random.randn(4,5)

array([[-1.80155105, -0.15616501, -1.55714094,  1.42818682, -1.29916919],
       [ 0.94539149, -0.07284409,  0.5219115 ,  0.6653166 ,  1.03998256],
       [-0.92291904, -1.21782261,  0.32931516,  0.20523244,  0.77445059],
       [ 0.13865622,  2.51604825,  0.15017984,  0.31183021, -0.78850241]])

In [45]:
pd.DataFrame(np.random.randn(4,5))

0         1         2         3         4
0  0.372968 -1.003012 -0.428396 -0.506955 -0.785056
1  0.558726  1.061864 -0.047239  0.153819 -2.523857
2  0.364873  0.173865 -0.148647  0.268091 -0.126250
3  1.581120 -0.376068 -1.243285  0.305370 -0.441084

In [ ]:
# three dimension array convert into two dimenstion array and 
# create the dataframe with two dimension array.



In [51]:
a2 = np.fromfunction(lambda i,j,z: i*j*z, (4,3,2),dtype = int)

In [52]:
a2

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 1],
        [0, 2]],

       [[0, 0],
        [0, 2],
        [0, 4]],

       [[0, 0],
        [0, 3],
        [0, 6]]])

In [54]:
# i can use reshape function to manupulation array 

a2.reshape(5,5)

ValueError: cannot reshape array of size 24 into shape (5,5)

In [55]:
a2.reshape(8,3)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 0, 2],
       [0, 0, 0],
       [2, 0, 4],
       [0, 0, 0],
       [3, 0, 6]])

In [56]:
pd.DataFrame(a2.reshape(8,3))

0  1  2
0  0  0  0
1  0  0  0
2  0  0  0
3  1  0  2
4  0  0  0
5  2  0  4
6  0  0  0
7  3  0  6

In [60]:
a2.reshape(4,2,1,3)

array([[[[0, 0, 0]],

        [[0, 0, 0]]],


       [[[0, 0, 0]],

        [[1, 0, 2]]],


       [[[0, 0, 0]],

        [[2, 0, 4]]],


       [[[0, 0, 0]],

        [[3, 0, 6]]]])

In [8]:
pd.DataFrame(np.random.randn(4,5))

0         1         2         3         4
0  0.787458  0.029954 -1.756851  0.341927  1.522489
1 -0.059974 -0.593614 -0.733339  0.021831 -0.915612
2  1.587917 -0.056972 -0.058837 -1.762880  0.125551
3 -0.882217  0.675640  1.249896 -0.761691 -0.763772

In [9]:
list(range(4,10))

[4, 5, 6, 7, 8, 9]

In [61]:
list(range(4,10,2))

[4, 6, 8]

In [10]:
list(range(4,10,.2))  # genarete error

# The range function is used with the integer data type.

TypeError: 'float' object cannot be interpreted as an integer

In [7]:
np.arange(4,10,.2)

# If I do the same task with arange function, this function will display the output

array([4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4,
       6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. ,
       9.2, 9.4, 9.6, 9.8])

In [12]:
al=np.arange(4,10.5,.2)

In [13]:
al

array([ 4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,
        6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,
        8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4])

In [14]:
# siling 

al[1:4]

array([4.2, 4.4, 4.6])

In [15]:
arr = np.random.rand(4,5)

In [16]:
arr

array([[0.92867644, 0.10945374, 0.54611845, 0.50933036, 0.45569704],
       [0.83772027, 0.30993666, 0.87013766, 0.98954479, 0.0226838 ],
       [0.84151156, 0.44800211, 0.16134676, 0.00234563, 0.51346   ],
       [0.93348633, 0.41257703, 0.50238939, 0.18594576, 0.61058267]])

In [17]:
# extract the value from given the array.

arr > .5

array([[ True, False,  True,  True, False],
       [ True, False,  True,  True, False],
       [ True, False, False, False,  True],
       [ True, False,  True, False,  True]])

In [18]:
arr[arr > .5]

array([0.92867644, 0.54611845, 0.50933036, 0.83772027, 0.87013766,
       0.98954479, 0.84151156, 0.51346   , 0.93348633, 0.50238939,
       0.61058267])

In [23]:
# extract the data by row and conmul from arr 

arr[[1,2],[2]]



array([0.87013766, 0.16134676])

In [20]:
arr1 = np.random.rand(8,5)

In [21]:
arr1

array([[0.30310537, 0.92703705, 0.78026843, 0.27321202, 0.61016101],
       [0.0085542 , 0.08564626, 0.82725488, 0.0926838 , 0.10950646],
       [0.32525528, 0.19008709, 0.43917127, 0.96085137, 0.50720515],
       [0.44580701, 0.2695651 , 0.60887585, 0.27666263, 0.82308129],
       [0.52938717, 0.68887438, 0.66363881, 0.06082241, 0.24853164],
       [0.21334827, 0.62432794, 0.04022434, 0.87696738, 0.92679112],
       [0.35594692, 0.47842915, 0.7503813 , 0.55758822, 0.79183737],
       [0.07049075, 0.22445425, 0.17848992, 0.739188  , 0.00730978]])

In [29]:
# extract the data by row and conmul.

arr1[[]]

array([0.0085542, 0.739188 ])

In [30]:
arr1[1:8 , 0:3]

array([[0.0085542 , 0.08564626, 0.82725488],
       [0.32525528, 0.19008709, 0.43917127],
       [0.44580701, 0.2695651 , 0.60887585],
       [0.52938717, 0.68887438, 0.66363881],
       [0.21334827, 0.62432794, 0.04022434],
       [0.35594692, 0.47842915, 0.7503813 ],
       [0.07049075, 0.22445425, 0.17848992]])

In [36]:
# multiplication of two array.

b = np.array([[2,3] , [4,5]])
a = np.array([[1,2] , [3,4]])

In [37]:
a

array([[1, 2],
       [3, 4]])

In [38]:
b

array([[2, 3],
       [4, 5]])

In [39]:
a*b

array([[ 2,  6],
       [12, 20]])

In [40]:
# matrix multipliction.

a@b

# @ is reprasent the matrix multipliction.


array([[10, 13],
       [22, 29]])