In [1]:
# video link =  https://learn.ineuron.ai/lesson/13th-March-live-class/622e923f528fc529c655ffb0/course/Full-Stack-Data-Science-Upcoming-batch/61b30b40b733d139bc0e7ffb/batch/61b30b40b733d139bc0e6ffe

# lecture name = 13th march live class.


In [2]:
import numpy as np

In [3]:
# this list convert into array.

l = [1,2,3,4,5,6]


In [4]:
np.asarray(l)

array([1, 2, 3, 4, 5, 6])

In [5]:
# zeros() it is a inbild function in numpy.

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np. zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [7]:
# antehr functio is ones().

np.ones(5)


array([1., 1., 1., 1., 1.])

In [8]:
np.ones((3,6,2))


# so create array with number of dimention.

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
5+np.zeros((3,4))

# 5 is here on scalar quantity withouth any direction 

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [11]:
# anther kid of array able to ganaret empty.
# empty is function of array numpy.
# it's look like empty but is not empty value.

np.empty((4,5))

array([[1.35837043e-311, 6.27463370e-322, 0.00000000e+000,
        0.00000000e+000, 1.69119330e-306],
       [5.30276956e+180, 6.74640243e-067, 6.97530945e-076,
        3.66039864e-086, 3.35908913e-143],
       [6.01433264e+175, 6.93885958e+218, 5.56218858e+180,
        3.94356143e+180, 7.49551120e-067],
       [6.81788507e-038, 6.52052856e-042, 1.27975840e+165,
        7.11391245e-144, 1.50008929e+248]])

In [12]:
# some inbild function just like a lonespace().

np.linspace(2,6)

array([2.        , 2.08163265, 2.16326531, 2.24489796, 2.32653061,
       2.40816327, 2.48979592, 2.57142857, 2.65306122, 2.73469388,
       2.81632653, 2.89795918, 2.97959184, 3.06122449, 3.14285714,
       3.2244898 , 3.30612245, 3.3877551 , 3.46938776, 3.55102041,
       3.63265306, 3.71428571, 3.79591837, 3.87755102, 3.95918367,
       4.04081633, 4.12244898, 4.20408163, 4.28571429, 4.36734694,
       4.44897959, 4.53061224, 4.6122449 , 4.69387755, 4.7755102 ,
       4.85714286, 4.93877551, 5.02040816, 5.10204082, 5.18367347,
       5.26530612, 5.34693878, 5.42857143, 5.51020408, 5.59183673,
       5.67346939, 5.75510204, 5.83673469, 5.91836735, 6.        ])

In [13]:
np.linspace(2,6,1000)

array([2.        , 2.004004  , 2.00800801, 2.01201201, 2.01601602,
       2.02002002, 2.02402402, 2.02802803, 2.03203203, 2.03603604,
       2.04004004, 2.04404404, 2.04804805, 2.05205205, 2.05605606,
       2.06006006, 2.06406406, 2.06806807, 2.07207207, 2.07607608,
       2.08008008, 2.08408408, 2.08808809, 2.09209209, 2.0960961 ,
       2.1001001 , 2.1041041 , 2.10810811, 2.11211211, 2.11611612,
       2.12012012, 2.12412412, 2.12812813, 2.13213213, 2.13613614,
       2.14014014, 2.14414414, 2.14814815, 2.15215215, 2.15615616,
       2.16016016, 2.16416416, 2.16816817, 2.17217217, 2.17617618,
       2.18018018, 2.18418418, 2.18818819, 2.19219219, 2.1961962 ,
       2.2002002 , 2.2042042 , 2.20820821, 2.21221221, 2.21621622,
       2.22022022, 2.22422422, 2.22822823, 2.23223223, 2.23623624,
       2.24024024, 2.24424424, 2.24824825, 2.25225225, 2.25625626,
       2.26026026, 2.26426426, 2.26826827, 2.27227227, 2.27627628,
       2.28028028, 2.28428428, 2.28828829, 2.29229229, 2.29629

In [14]:
np.linspace(2,6,10)

array([2.        , 2.44444444, 2.88888889, 3.33333333, 3.77777778,
       4.22222222, 4.66666667, 5.11111111, 5.55555556, 6.        ])

In [15]:
np.linspace(2,6,10).reshape(5,2)

array([[2.        , 2.44444444],
       [2.88888889, 3.33333333],
       [3.77777778, 4.22222222],
       [4.66666667, 5.11111111],
       [5.55555556, 6.        ]])

In [16]:
np.linspace(2,6,10,endpoint = False).reshape(5,2)

# upper case value and lowercase value.

array([[2. , 2.4],
       [2.8, 3.2],
       [3.6, 4. ],
       [4.4, 4.8],
       [5.2, 5.6]])

In [17]:
np.linspace(2,6,10,endpoint = False,retstep = True)

# step size

(array([2. , 2.4, 2.8, 3.2, 3.6, 4. , 4.4, 4.8, 5.2, 5.6]), 0.4)

In [18]:
np.linspace(2,6,100,endpoint = False,retstep = True)


(array([2.  , 2.04, 2.08, 2.12, 2.16, 2.2 , 2.24, 2.28, 2.32, 2.36, 2.4 ,
        2.44, 2.48, 2.52, 2.56, 2.6 , 2.64, 2.68, 2.72, 2.76, 2.8 , 2.84,
        2.88, 2.92, 2.96, 3.  , 3.04, 3.08, 3.12, 3.16, 3.2 , 3.24, 3.28,
        3.32, 3.36, 3.4 , 3.44, 3.48, 3.52, 3.56, 3.6 , 3.64, 3.68, 3.72,
        3.76, 3.8 , 3.84, 3.88, 3.92, 3.96, 4.  , 4.04, 4.08, 4.12, 4.16,
        4.2 , 4.24, 4.28, 4.32, 4.36, 4.4 , 4.44, 4.48, 4.52, 4.56, 4.6 ,
        4.64, 4.68, 4.72, 4.76, 4.8 , 4.84, 4.88, 4.92, 4.96, 5.  , 5.04,
        5.08, 5.12, 5.16, 5.2 , 5.24, 5.28, 5.32, 5.36, 5.4 , 5.44, 5.48,
        5.52, 5.56, 5.6 , 5.64, 5.68, 5.72, 5.76, 5.8 , 5.84, 5.88, 5.92,
        5.96]),
 0.04)

In [19]:
np.logspace(2,4,10,base = 2)

array([ 4.        ,  4.66611616,  5.44316   ,  6.34960421,  7.4069977 ,
        8.64047791, 10.0793684 , 11.75787594, 13.71590373, 16.        ])

In [20]:
a = np.arange(4,20).reshape(4,4)

In [21]:
a

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [22]:
a.max()

# video time 45m

19

In [23]:
a.max(axis = 1)

# This is the column wise rsult

array([ 7, 11, 15, 19])

In [24]:
a.max(axis = 0)

# This is the row wise result 

array([16, 17, 18, 19])

In [25]:
10 + a

array([[14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29]])

In [26]:
a/0

# answer is infity

<ipython-input-26-aa50b7e4c557>:1: RuntimeWarning: divide by zero encountered in true_divide
  a/0


array([[inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf],
       [inf, inf, inf, inf]])

In [27]:
a**2

array([[ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225],
       [256, 289, 324, 361]], dtype=int32)

In [28]:
pow(a,3)

array([[  64,  125,  216,  343],
       [ 512,  729, 1000, 1331],
       [1728, 2197, 2744, 3375],
       [4096, 4913, 5832, 6859]], dtype=int32)

In [29]:
a

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [30]:
b = np.array([2,3,1,2])

In [31]:
b

array([2, 3, 1, 2])

In [32]:
a+b

array([[ 6,  8,  7,  9],
       [10, 12, 11, 13],
       [14, 16, 15, 17],
       [18, 20, 19, 21]])

In [33]:
# rutate this array for addition or trancpose 

c = np.array([2,3,1,2])

In [34]:
c = c.T

In [35]:
a+c

array([[ 6,  8,  7,  9],
       [10, 12, 11, 13],
       [14, 16, 15, 17],
       [18, 20, 19, 21]])

In [36]:
c1 =c.reshape(1,-1) 

In [37]:
c1

array([[2, 3, 1, 2]])

In [38]:
c1.T

array([[2],
       [3],
       [1],
       [2]])

In [39]:
c1 + a

array([[ 6,  8,  7,  9],
       [10, 12, 11, 13],
       [14, 16, 15, 17],
       [18, 20, 19, 21]])

In [40]:
a

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [41]:
a+b

array([[ 6,  8,  7,  9],
       [10, 12, 11, 13],
       [14, 16, 15, 17],
       [18, 20, 19, 21]])

In [42]:
# find the square root of each and every element of array.

np.sqrt(a)

array([[2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894]])

In [43]:
# find the exponate of each and every element of array.

np.exp(a)

array([[5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04],
       [1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06],
       [8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08]])

In [45]:
np.log10(a)

array([[0.60205999, 0.69897   , 0.77815125, 0.84509804],
       [0.90308999, 0.95424251, 1.        , 1.04139269],
       [1.07918125, 1.11394335, 1.14612804, 1.17609126],
       [1.20411998, 1.23044892, 1.25527251, 1.2787536 ]])